
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrlveiqgljzcyjxuvvad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ybHZlaXFnbGp6Y3lqeHV2dmFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNzc4MjMsImV4cCI6MjA1Nzk1MzgyM30.xPS2FR1FrCJlVH_SA6rQxAiwhhJ6Rzn7cRRcsBrOqh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
